brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,

)


urlpatterns = [
    path("", TodoListListView.as_view(), name = "todo_list_list"),
    path("<int:pk>/",TodoListDetailView.as_view(), name = "todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name = "todo_list_create"),
    path("<int:pk>/edit/", TodoListUpdateView.as_view(), name = "todo_list_update"),
    path("<int:pk>/delete/", TodoListDeleteView.as_view(), name = "todo_list_delete"),
    path("items/create/", TodoItemCreateView.as_view(), name = "todo_item_create"),
    path("items/<int:pk>/edit/", TodoItemUpdateView.as_view(), name = "todo_item_update"),
]

todos/models.py
from django.db import models

# Create your models here.

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey("TodoList", related_name= "items", on_delete=models.CASCADE)

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from todos.models import TodoList, TodoItem
# Create your views here.

class TodoListListView(ListView):
    model = TodoList
    template_name = "todos/list.html"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        print(queryset)
        return queryset

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        print(context)
        return context

class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        print(queryset)
        return queryset

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        print(context)
        return context

class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/new.html"
    fields = ["name"]

    def form_valid(self,form):
        form.instance.author=self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy('todo_list_list')

class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/create.html"
    fields = ["task", "due_date", "is_completed" , "list"]

    def form_valid(self,form):
        form.instance.author=self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todos/edititem.html"
    fields = ["task", "due_date", "is_completed" , "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                  <button class="button">Create</button>
              </form>
        </div>
    </main>

</body>
</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                  <button class="button">Delete</button>
                </div>
              </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1> {{ todolist.name }} </h1>
            <div>
                <p><a href="{% url 'todo_list_list' %}">Home</a></p>
                  <p><a href="{% url 'todo_list_update' todolist.pk %}">Edit</a></p>
                  <p><a href="{% url 'todo_list_delete' todolist.pk %}">Delete</a></p>
            </div>
            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in todolist.items.all %}
                    <tr>
                        <td><a href="{% url 'todo_item_update' item.pk %}">{{item.task}}</td>
                        <td>{{item.due_date}}</td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </main>

</body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Update List</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                  <button class="button">Update</button>
              </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/edititem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Update Item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                  <button class="button">Update</button>
              </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <div>
                <p>
                    <a href="{% url 'todo_list_create' %}">Create a new list</a>
                </p>
                <p>
                    <a href="{% url 'todo_item_create' %}">Create a new item</a>
                </p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for list in todolist_list %}
                    <tr>
                        <td><a href="{% url 'todo_list_detail' list.pk %}">{{list.name}}</td>
                        <td> {{list.items.all|length}} </td>
                    {%endfor%}
                    </tr>
                </tbody>

            </table>
        </div>
    </main>

</body>
</html>

todos/templates/todos/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                  <button class="button">Create</button>
                </div>
              </form>
        </div>
    </main>

</body>
</html>